package de.elegantsoftware.blitzpay.product.support

import de.elegantsoftware.blitzpay.product.api.ProductService
import de.elegantsoftware.blitzpay.product.domain.Price
import de.elegantsoftware.blitzpay.product.domain.Product
import de.elegantsoftware.blitzpay.product.domain.ProductId
import de.elegantsoftware.blitzpay.product.domain.ProductInventory
import de.elegantsoftware.blitzpay.product.domain.ProductStatus
import de.elegantsoftware.blitzpay.product.domain.ProductType
import de.elegantsoftware.blitzpay.product.domain.ProductVariant
import de.elegantsoftware.blitzpay.product.domain.events.*
import de.elegantsoftware.blitzpay.product.outbound.persistence.ProductRepository
import de.elegantsoftware.blitzpay.product.support.exception.*
import de.elegantsoftware.blitzpay.product.support.mapper.ProductJpaMapper
import org.slf4j.LoggerFactory
import org.springframework.context.ApplicationEventPublisher
import org.springframework.data.domain.Page
import org.springframework.data.domain.Pageable
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.math.BigDecimal
import java.util.*
import kotlin.time.Clock

@Service
@Transactional
class ProductServiceImpl(
    private val productRepository: ProductRepository,
    private val productJpaMapper: ProductJpaMapper,
    private val eventPublisher: ApplicationEventPublisher,
) : ProductService {

    private val logger = LoggerFactory.getLogger(ProductServiceImpl::class.java)

    override fun createProduct(
        merchantId: Long,
        name: String,
        description: String,
        type: ProductType,
        basePrice: BigDecimal,
        currency: String,
        variants: List<ProductVariant>,
        initialStock: Int,
        trackInventory: Boolean,
        categoryId: Long?,
        tags: Set<String>,
        metadata: Map<String, String>
    ): Product {
        // Validate price
        if (basePrice < BigDecimal.ZERO) {
            throw InvalidPriceException(price = basePrice, field = "basePrice")
        }

        // Validate initial stock
        if (initialStock < 0) {
            throw ProductValidationException(
                field = "initialStock",
                message = "Initial stock must be non-negative"
            )
        }

        // Validate SKU uniqueness
        variants.forEach { variant ->
            if (productRepository.existsBySkuAndMerchantId(variant.sku, merchantId)) {
                throw DuplicateSkuException(variant.sku, merchantId)
            }

            // Validate variant price
            if (variant.price.amount < BigDecimal.ZERO) {
                throw InvalidPriceException(price = variant.price.amount, field = "variant.${variant.sku}.price")
            }
        }

        // Create domain ProductVariant objects from ProductVariantData
        val productVariants = variants.map { variantData ->
            ProductVariant(
                // id will be generated by default in the ProductVariant constructor
                sku = variantData.sku,
                name = variantData.name,
                price = Price(
                    amount = variantData.price.amount,
                    currency = variantData.price.currency
                ),
                attributes = variantData.attributes
            )
        }

        val now = Clock.System.now()
        val product = Product(
            id = ProductId(0),
            publicId = UUID.randomUUID(),
            merchantId = merchantId,
            name = name,
            description = description,
            type = type,
            status = ProductStatus.DRAFT,
            basePrice = Price(
                amount = basePrice,
                currency = currency
            ),
            variants = productVariants,
            inventory = ProductInventory(
                quantity = initialStock,
                isTracked = trackInventory
            ),
            categoryId = categoryId,
            tags = tags,
            metadata = metadata,
            createdAt = now,
            updatedAt = now
        )

        val entity = productJpaMapper.toEntity(product)
        val savedEntity = productRepository.save(entity)
        val savedProduct = productJpaMapper.toDomain(savedEntity)

        // Publish domain event
        eventPublisher.publishEvent(ProductCreated.from(savedProduct))

        return savedProduct
    }

    override fun updateProduct(
        merchantId: Long,
        productPublicId: UUID,
        name: String?,
        description: String?,
        type: ProductType?,
        basePrice: BigDecimal?,
        currency: String?,
        variants: List<ProductVariant>?,
        categoryId: Long?,
        tags: Set<String>?,
        metadata: Map<String, String>?
    ): Product {
        val entity = productRepository.findByMerchantIdAndPublicId(merchantId, productPublicId)
            ?: throw ProductNotFoundException(publicId = productPublicId, merchantId = merchantId)

        val existingProduct = productJpaMapper.toDomain(entity)

        // Validate product is not archived
        if (existingProduct.status == ProductStatus.ARCHIVED) {
            throw InvalidProductStatusException(
                currentStatus = existingProduct.status,
                validStatuses = setOf(
                    ProductStatus.DRAFT,
                    ProductStatus.ACTIVE,
                    ProductStatus.INACTIVE
                )
            )
        }

        // Track updated fields for event
        val updatedFields = mutableSetOf<String>()

        // Validate price if being updated
        if (basePrice != null && basePrice < BigDecimal.ZERO) {
            throw InvalidPriceException(price = basePrice, field = "basePrice")
        }

        // Validate SKU uniqueness for new variants
        variants?.forEach { variantData ->
            if (!existingProduct.variants.any { it.sku == variantData.sku }) {
                if (productRepository.existsBySkuAndMerchantId(variantData.sku, merchantId)) {
                    throw DuplicateSkuException(variantData.sku, merchantId)
                }
            }

            // Validate variant price
            if (variantData.price.amount < BigDecimal.ZERO) {
                throw InvalidPriceException(price = variantData.price.amount, field = "variant.${variantData.sku}.price")
            }
        }

        val updatedVariants = if (variants != null) {
            updatedFields.add("variants")
            variants.map { variantData ->
                val existingVariant = existingProduct.variants.find { it.sku == variantData.sku }
                existingVariant?.copy(
                    name = variantData.name,
                    price = Price(
                        amount = variantData.price.amount,
                        currency = variantData.price.currency
                    ),
                    attributes = variantData.attributes
                ) ?: ProductVariant(
                    sku = variantData.sku,
                    name = variantData.name,
                    price = Price(
                        amount = variantData.price.amount,
                        currency = variantData.price.currency
                    ),
                    attributes = variantData.attributes
                )
            }
        } else {
            existingProduct.variants
        }
        val newName = name?.also { updatedFields.add("name") } ?: existingProduct.name
        val newDescription = description?.also { updatedFields.add("description") } ?: existingProduct.description
        val newType = type?.also { updatedFields.add("type") } ?: existingProduct.type
        val newCategoryId = categoryId?.also { updatedFields.add("categoryId") } ?: existingProduct.categoryId
        val newTags = tags?.also { updatedFields.add("tags") } ?: existingProduct.tags
        val newMetadata = metadata?.also { updatedFields.add("metadata") } ?: existingProduct.metadata
        val newBasePrice =
            if (basePrice != null && currency != null) {
                updatedFields.add("basePrice")
                Price(basePrice, currency)
            } else {
                existingProduct.basePrice
            }
        val updatedProduct = existingProduct.copy(
            name = newName,
            description = newDescription,
            type = newType,
            basePrice = newBasePrice,
            variants = updatedVariants,
            categoryId = newCategoryId,
            tags = newTags,
            metadata = newMetadata,
            updatedAt = Clock.System.now()
        )

        val updatedEntity = productJpaMapper.updateEntity(entity, updatedProduct)
        val savedEntity = productRepository.save(updatedEntity)
        val savedProduct = productJpaMapper.toDomain(savedEntity)

        // Publish domain event if any fields were updated
        if (updatedFields.isNotEmpty()) {
            eventPublisher.publishEvent(ProductUpdated.from(savedProduct, updatedFields))
        }

        return savedProduct
    }

    override fun getProduct(merchantId: Long, productPublicId: UUID): Product {
        val entity = productRepository.findByMerchantIdAndPublicId(merchantId, productPublicId)
            ?: throw ProductNotFoundException(publicId = productPublicId, merchantId = merchantId)
        return productJpaMapper.toDomain(entity)
    }

    override fun getProductById(productId: ProductId): Product {
        val entity = productRepository.findById(productId.value).orElse(null)
            ?: throw ProductNotFoundException(productId = productId)
        return productJpaMapper.toDomain(entity)
    }

    override fun getProductsByIds(productIds: List<UUID>): List<Product> {
        logger.info("Getting products by public IDs: {}", productIds)

        if (productIds.isEmpty()) {
            return emptyList()
        }

        return try {
            // FIXED: Repository returns List<ProductJpaEntity>, need to map to Product
            productRepository.findByPublicIdIn(productIds)
                .map { productJpaMapper.toDomain(it) }
        } catch (e: Exception) {
            logger.error("Failed to get products by public IDs: $productIds", e)
            emptyList()
        }
    }

    override fun getTotalPrice(productIds: List<UUID>): BigDecimal {
        logger.info("Calculating total price for products: {}", productIds)

        if (productIds.isEmpty()) {
            return BigDecimal.ZERO
        }

        return try {
            productRepository.findByPublicIdIn(productIds)
                .fold(BigDecimal.ZERO) { acc, entity -> acc.add(entity.basePriceAmount) }
        } catch (e: Exception) {
            logger.error("Failed to calculate total price for products: $productIds", e)
            BigDecimal.ZERO
        }
    }

    override fun getProductsByPublicIds(merchantId: Long, productPublicIds: List<UUID>): List<Product> {
        logger.info("Getting products for merchant {} by public IDs: {}", merchantId, productPublicIds)

        return try {
            // FIXED: Repository returns List<ProductJpaEntity>, need to map to Product
            productRepository.findByMerchantIdAndPublicIdIn(merchantId, productPublicIds)
                .map { productJpaMapper.toDomain(it) }
        } catch (e: Exception) {
            logger.error("Failed to get products for merchant $merchantId by public IDs: $productPublicIds", e)
            emptyList()
        }
    }

    override fun listProducts(merchantId: Long, pageable: Pageable): Page<Product> {
        return productRepository.findAllByMerchantId(merchantId, pageable)
            .map { productJpaMapper.toDomain(it) }
    }

    override fun searchProducts(
        merchantId: Long,
        query: String,
        status: ProductStatus?,
        type: ProductType?,
        pageable: Pageable
    ): Page<Product> {
        return productRepository.searchByMerchantId(
            merchantId = merchantId,
            query = query.ifBlank { null },
            status = status,  // FIXED: Pass enum directly, not .name
            type = type,      // FIXED: Pass enum directly, not .name
            pageable = pageable
        ).map { productJpaMapper.toDomain(it) }
    }

    override fun deleteProduct(merchantId: Long, productPublicId: UUID) {
        val entity = productRepository.findByMerchantIdAndPublicId(merchantId, productPublicId)
            ?: throw ProductNotFoundException(publicId = productPublicId, merchantId = merchantId)

        val product = productJpaMapper.toDomain(entity)
        productRepository.deleteById(entity.id!!)

        // Publish domain event
        eventPublisher.publishEvent(
            ProductArchived(
                productId = product.publicId,
                merchantId = product.merchantId,
                archivedAt = Clock.System.now()
            )
        )
    }

    override fun changeProductStatus(merchantId: Long, productPublicId: UUID, status: ProductStatus) {
        val entity = productRepository.findByMerchantIdAndPublicId(merchantId, productPublicId)
            ?: throw ProductNotFoundException(publicId = productPublicId, merchantId = merchantId)

        val product = productJpaMapper.toDomain(entity)

        // Validate status transition
        when (product.status) {
            ProductStatus.ARCHIVED -> throw InvalidProductStatusException(
                currentStatus = product.status,
                validStatuses = emptySet() // Or setOf() to indicate no valid transitions
            )
            ProductStatus.DRAFT -> {
                if (status != ProductStatus.ACTIVE && status != ProductStatus.INACTIVE) {
                    throw InvalidProductStatusException(
                        currentStatus = product.status,
                        validStatuses = setOf(ProductStatus.ACTIVE, ProductStatus.INACTIVE)
                    )
                }
            }
            // Add more status validation rules as needed
            ProductStatus.ACTIVE -> {
                if (status != ProductStatus.INACTIVE && status != ProductStatus.ARCHIVED) {
                    throw InvalidProductStatusException(
                        currentStatus = product.status,
                        validStatuses = setOf(ProductStatus.INACTIVE, ProductStatus.ARCHIVED)
                    )
                }
            }
            ProductStatus.INACTIVE -> {
                if (status != ProductStatus.ACTIVE && status != ProductStatus.ARCHIVED) {
                    throw InvalidProductStatusException(
                        currentStatus = product.status,
                        validStatuses = setOf(ProductStatus.ACTIVE, ProductStatus.ARCHIVED)
                    )
                }
            }
        }

        val updatedProduct = product.copy(
            status = status,
            updatedAt = Clock.System.now()
        )

        val updatedEntity = productJpaMapper.updateEntity(entity, updatedProduct)
        productRepository.save(updatedEntity)

        // Publish domain event
        eventPublisher.publishEvent(
            ProductUpdated.from(updatedProduct, setOf("status"))
        )
    }

    override fun adjustStock(merchantId: Long, productPublicId: UUID, adjustment: Int): Product {
        val entity = productRepository.findByMerchantIdAndPublicId(merchantId, productPublicId)
            ?: throw ProductNotFoundException(publicId = productPublicId, merchantId = merchantId)

        val product = productJpaMapper.toDomain(entity)

        if (!product.inventory.isTracked) {
            throw InventoryTrackingDisabledException(productPublicId)
        }

        // FIXED: Check if domain class has these methods, or implement them
        if (adjustment < 0) {
            val quantityToReduce = -adjustment
            if (product.inventory.quantity < quantityToReduce) {
                throw InsufficientStockException(
                    productPublicId = productPublicId,
                    requestedQuantity = quantityToReduce,
                    availableQuantity = product.inventory.quantity
                )
            }
        }

        val updatedInventory = product.inventory.copy(
            quantity = product.inventory.quantity + adjustment
        )

        val updatedProduct = product.copy(
            inventory = updatedInventory,
            updatedAt = Clock.System.now()
        )

        val updatedEntity = productJpaMapper.updateEntity(entity, updatedProduct)
        val savedEntity = productRepository.save(updatedEntity)
        val savedProduct = productJpaMapper.toDomain(savedEntity)

        // Publish domain event
        eventPublisher.publishEvent(
            ProductStockAdjusted(
                productId = savedProduct.publicId,
                merchantId = savedProduct.merchantId,
                oldQuantity = product.inventory.quantity,
                newQuantity = savedProduct.inventory.quantity,
                adjustment = adjustment
            )
        )

        return savedProduct
    }

    override fun updatePrice(merchantId: Long, productPublicId: UUID, newPrice: BigDecimal, currency: String): Product {
        val entity = productRepository.findByMerchantIdAndPublicId(merchantId, productPublicId)
            ?: throw ProductNotFoundException(publicId = productPublicId, merchantId = merchantId)

        val product = productJpaMapper.toDomain(entity)

        if (newPrice < BigDecimal.ZERO) {
            throw InvalidPriceException(price = newPrice, field = "newPrice")
        }

        val oldPrice = product.basePrice
        val updatedProduct = product.copy(
            basePrice = Price(amount = newPrice, currency = currency),
            updatedAt = Clock.System.now()
        )

        val updatedEntity = productJpaMapper.updateEntity(entity, updatedProduct)
        val savedEntity = productRepository.save(updatedEntity)
        val savedProduct = productJpaMapper.toDomain(savedEntity)

        // Publish domain event
        eventPublisher.publishEvent(
            ProductPriceChanged(
                productId = savedProduct.publicId,
                merchantId = savedProduct.merchantId,
                oldPrice = oldPrice.amount,
                oldCurrency = oldPrice.currency,
                newPrice = newPrice,
                newCurrency = currency
            )
        )

        return savedProduct
    }
}