name: CD pipeline

on:
  release:
    types:
      - published

jobs:
  ci:
    permissions:
      actions: write
      contents: write
      checks: write
      pull-requests: write
    uses: ./.github/workflows/ci.yml
  release:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    #needs: ci
    if: github.event_name == 'release'
    uses: elegant-software/elegant-ci-cd-pipeline/.github/workflows/backend-docker-build.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}
      image-name: ${{ vars.APP_NAME }}
      image-tag: ${{ github.ref_name }}
      registry: ${{ vars.CONTAINER_REGISTRY }}