name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_call:
    inputs:
      gradle-args:
        required: false
        type: string
        default: ""

env:
  ORG_GRADLE_PROJECT_javaVersion: ${{ vars.JAVA_VERSION }}

jobs:
  test:
      permissions:
        contents: read
      uses: medimohammadise/elegant-ci-cd-pipeline/.github/workflows/backend-gradle-test.yml@main
      with:
        gradle-args: ${{ inputs.gradle-args }}
        unit-test-task: test
        integration-test-task: help

  qodana_code_quality:
    name: qodana
    needs: test
    permissions:
      contents: write
      pull-requests: write
      checks: write
    uses: medimohammadise/elegant-ci-cd-pipeline/.github/workflows/backend-qa-qodana-code-quality.yml@main
    secrets: inherit

  sbom-upload:
    name: dependency track & SBOM upload
    needs: test
    permissions:
      contents: read
    uses: medimohammadise/elegant-ci-cd-pipeline/.github/workflows/backnd-qa-dependency-track-upload.yml@main
    secrets: inherit
